language: python
sudo: false

# matrix start ###################################

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx
  include:
    - os: osx
      language: generic
      env: TOXENV='2.7'
    - os: osx
      language: generic
      env: TOXENV='3.4'
    - os: osx
      language: generic
      env: TOXENV='3.5'
    - os: osx
      language: generic
      env: TOXENV='3.6'

# matrix end #####################################

cache:
  directories:
    - $HOME/.m2
    - $HOME/.pyenv

addons:
  apt:
    packages:
      # update java8 to latest version
      - oracle-java8-installer

before_script:
  - travis_wait 20 mvn dependency:resolve
  - bash ./ci/travis/before_script.sh
  - pyenv activate jpy-venv
  - pip install wheel

script: python setup.py --maven bdist_wheel
