language: java
sudo: false

jdk:
  - "oraclejdk8"
  - "openjdk8"

cache:
 directories:
   - $HOME/.m2

addons:
  apt:
    packages:
      - oracle-java8-installer
      - python-dev

before_script:
  - travis_wait 20 mvn dependency:resolve
  - pip install wheel

script: python setup.py --maven bdist_wheel
install:
  - python setup.py install
  - mvn install
