language: python
sudo: false

# matrix start ###################################

matrix:
  allow_failures:
    - os: osx
  include:
    # Linux -----------------------
    - os: linux
      language: python
      python: 2.7
    - os: linux
      language: python
      python: 3.4
    - os: linux
      language: python
      python: 3.5
    - os: linux
      language: python
      python: 3.6
    # OS-X ------------------------
    - os: osx
      language: generic
      env: PYTHON_VERSION='2.7'
    - os: osx
      language: generic
      # exact version required: 3.4  is not available
      env: PYTHON_VERSION='3.4.7'
    - os: osx
      language: generic
      env: PYTHON_VERSION='3.5.4'
    - os: osx
      language: generic
      env: PYTHON_VERSION='3.6.4'

# matrix end #####################################

cache:
  directories:
    - $HOME/.m2
    - $HOME/.pyenv

addons:
  apt:
    packages:
      # update java8 to latest version
      - oracle-java8-installer
      - oracle-java8-set-default

before_script:
  - travis_wait 20 mvn dependency:resolve
  - bash ./ci/travis/before_script.sh

script:
  - bash ./ci/travis/run.sh
