language: java
sudo: false

jdk:
  - "oraclejdk8"

cache:
 directories:
   - $HOME/.m2

addons:
  apt:
    packages:
      - python-dev

before_script:
  - travis_wait 20 mvn dependency:resolve
  - pip --user install wheel

script: python setup.py --maven bdist_wheel
