image: Visual Studio 2015

environment:
  matrix:
    - PYTHON_HOME: C:\Python27-x64
    - PYTHON_HOME: C:\Python34-x64
    - PYTHON_HOME: C:\Python35-x64
    - PYTHON_HOME: C:\Python36-x64

cache:
  - '%UserProfile%\.m2'

before_build:
  - cmd: call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64

build:
  - cmd: set JDK_HOME=C:\Program Files\Java\jdk1.8.0
  - cmd: set JAVA_HOME=%JDK_HOME%
  #- cmd: set PATH=%PYTHON_HOME%\%PATH%
  - cmd: echo %PYTHON_HOME%
  - cmd: %PYTHON_HOME%\python.exe setup.py --maven bdist_wheel


